tasks:
  - name: Setup .env
    init: >
      cp .env.example .env &&
      sed -i "s|APP_URL=http://localhost|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env

  - name: Get Laravel Sail dependencies via docker
    init: >
      docker run --rm -u "$(id -u):$(id -g)" -v "$(pwd):/app" -w /app composer:2 composer install --ignore-platform-reqs &&
      gp sync-done composer

  - name: Execute Laravel Sail
    init: gp sync-await composer
    command: >
      ./vendor/bin/sail up -d &&
      gp sync-done sail-up

  - name: Run dev
    before: gp sync-await sail-up
    init: ./vendor/bin/sail php artisan key:generate && ./vendor/bin/sail php artisan storage:link
    command: >
      ./vendor/bin/sail composer install &&
      ./vendor/bin/sail npm install &&
      ./vendor/bin/sail php artisan migrate &&
      ./vendor/bin/sail npm run dev

ports:
  - port: 5173
    onOpen: ignore
    visibility: public
    name: Vite